### ISSUE TITLE
Storybook failing to find variable: exports

### ISSUE THREAD

**Issue by shp7724** [researchgate/react-intersection-observer#139]
Thanks for taking the time to file an issue with us.
Please note that this issue template is used **ONLY** for reporting bugs.

If you have an issue that isn’t a bug, please follow the steps listed in the [Contributing](CONTRIBUTING.md).
Thanks!

## Expected behavior

```https://researchgate.github.io/react-intersection-observer/?path=/story/*``` should open without errors.

## Current behavior

In Chrome:
```
ReferenceError: exports is not defined
    at Module.728 (https://researchgate.github.io/react-intersection-observer/main.28ed3cace93a70069515.bundle.js:1:62602)
    at __webpack_require__ (https://researchgate.github.io/react-intersection-observer/runtime~main.28ed3cace93a70069515.bundle.js:1:1301)
    at Object.28 (https://researchgate.github.io/react-intersection-observer/main.28ed3cace93a70069515.bundle.js:1:1765)
    at __webpack_require__ (https://researchgate.github.io/react-intersection-observer/runtime~main.28ed3cace93a70069515.bundle.js:1:1301)
    at Object.309 (https://researchgate.github.io/react-intersection-observer/main.28ed3cace93a70069515.bundle.js:1:20958)
    at __webpack_require__ (https://researchgate.github.io/react-intersection-observer/runtime~main.28ed3cace93a70069515.bundle.js:1:1301)
    at Module.<anonymous> (https://researchgate.github.io/react-intersection-observer/main.28ed3cace93a70069515.bundle.js:1:60576)
    at Module.641 (https://researchgate.github.io/react-intersection-observer/main.28ed3cace93a70069515.bundle.js:1:62225)
    at __webpack_require__ (https://researchgate.github.io/react-intersection-observer/runtime~main.28ed3cace93a70069515.bundle.js:1:1301)
    at https://researchgate.github.io/react-intersection-observer/main.28ed3cace93a70069515.bundle.js:1:59968
```

In Safari:
```
Can't find variable: exports
https://researchgate.github.io/react-intersection-observer/main.28ed3cace93a70069515.bundle.js:1:62609
__webpack_require__@https://researchgate.github.io/react-intersection-observer/runtime~main.28ed3cace93a70069515.bundle.js:1:1305
https://researchgate.github.io/react-intersection-observer/main.28ed3cace93a70069515.bundle.js:1:1784
__webpack_require__@https://researchgate.github.io/react-intersection-observer/runtime~main.28ed3cace93a70069515.bundle.js:1:1305
https://researchgate.github.io/react-intersection-observer/main.28ed3cace93a70069515.bundle.js:1:20977
__webpack_require__@https://researchgate.github.io/react-intersection-observer/runtime~main.28ed3cace93a70069515.bundle.js:1:1305
https://researchgate.github.io/react-intersection-observer/main.28ed3cace93a70069515.bundle.js:1:60595
https://researchgate.github.io/react-intersection-observer/main.28ed3cace93a70069515.bundle.js:1:62229
__webpack_require__@https://researchgate.github.io/react-intersection-observer/runtime~main.28ed3cace93a70069515.bundle.js:1:1305
https://researchgate.github.io/react-intersection-observer/vendors~main.28ed3cace93a70069515.bundle.js:2:592055
render@https://researchgate.github.io/react-intersection-observer/vendors~main.28ed3cace93a70069515.bundle.js:2:572877
https://researchgate.github.io/react-intersection-observer/vendors~main.28ed3cace93a70069515.bundle.js:2:573096
configure@https://researchgate.github.io/react-intersection-observer/vendors~main.28ed3cace93a70069515.bundle.js:2:595005
https://researchgate.github.io/react-intersection-observer/main.28ed3cace93a70069515.bundle.js:1:59948
https://researchgate.github.io/react-intersection-observer/main.28ed3cace93a70069515.bundle.js:1:60008
__webpack_require__@https://researchgate.github.io/react-intersection-observer/runtime~main.28ed3cace93a70069515.bundle.js:1:1305
https://researchgate.github.io/react-intersection-observer/main.28ed3cace93a70069515.bundle.js:1:59273
__webpack_require__@https://researchgate.github.io/react-intersection-observer/runtime~main.28ed3cace93a70069515.bundle.js:1:1305
checkDeferredModules@https://researchgate.github.io/react-intersection-observer/runtime~main.28ed3cace93a70069515.bundle.js:1:976
webpackJsonpCallback@https://researchgate.github.io/react-intersection-observer/runtime~main.28ed3cace93a70069515.bundle.js:1:665
global code@https://researchgate.github.io/react-intersection-observer/main.28ed3cace93a70069515.bundle.js:1:51
```

## Steps to reproduce

1. Go to ```https://researchgate.github.io/react-intersection-observer/?path=/story/*```.
2. An error is found.
3.
4.

## Context (environment)

* **Version**: 
* **Platform**: macOS Catalina

**Comment by shp7724** [comment]
I found a working link ```https://react-intersection-observer.now.sh/``` at npm repository. The link in the github README seems to be deprecated.
